### ISSUE TITLE
Failed to compile file less

### ISSUE THREAD

**Issue by benitoanagua** [zkoss-demo/ui-examples#7]
When I try to compile, I get this error

> $ lessc index.less > index.css.dsp
> ParseError: Unrecognised input in ..._header.less on line 1, column 1:
> 1 <%@ taglib uri="http://www.zkoss.org/dsp/web/core" prefix="c" %>
> 2 <%@ taglib uri="http://www.zkoss.org/dsp/zk/core" prefix="z" %>

my English is limited, appreciate any help

**Comment by jumperchen** [comment]
Please follow the ZK instruction to compile the less file to a dsp file, which is different from the original less compiler. -  http://books.zkoss.org/wiki/ZK_Style_Customization_Guide/Integrate_with_LESS/How_ZK_works_with_LESS/Compile_LESS

**Comment by benitoanagua** [comment]
thanks
